; Initialization file for nanoclj

(load-file "bootstrap.clj")
(load-file "clojure.core.clj")
(load-file "clojure.java.io.clj")
(load-file "clojure.java.shell.clj")
(load-file "clojure.string.clj")
(load-file "clojure.repl.clj")
(load-file "java.lang.Object.clj")
(load-file "java.lang.Integer.clj")
(load-file "java.lang.Long.clj")
(load-file "java.lang.String.clj")
(load-file "java.util.Date.clj")
(load-file "sparkline.clj")
(load-file "Plot.clj")
(load-file "nanoclj.core.Codepoint.clj")
(load-file "nanoclj.core.Tensor.clj")
(load-file "nanoclj.image.clj")
