#include <stdio.h>

static inline void legal() {
  printf("\n"
	 "nanoclj\n"
	 "-----------\n"
	 "\n"
	 "Copyright (c) 1989, Atsushi Moriwaki\n"
	 "Copyright (c) 2000, Dimitrios Souflis\n"
	 "Copyright (c) 2007, Kevin Cozens\n"
	 "(and others - see AUTHORS)\n"
	 "\n"
	 "All rights reserved.\n"
	 "\n"
	 "Redistribution and use in source and binary forms, with or without\n"
	 "modification, are permitted provided that the following conditions are met:\n"
	 "\n"
	 "1. Redistributions of source code must retain the above copyright notice,\n"
	 "   AUTHORS file, this list of conditions and the following disclaimer.\n"
	 "\n"
	 "2. Redistributions in binary form must reproduce the above copyright notice,\n"
	 "   this list of conditions and the following disclaimer in the documentation\n"
	 "   and/or other materials provided with the distribution.\n"
	 "\n"
	 "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
	 "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
	 "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
	 "DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\n"
	 "FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
	 "DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
	 "SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
	 "CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
	 "OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
	 "OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
	 "\n"
	 "\n"
  
	 "Linenoise\n"
	 "---------\n"
	 "\n"
	 "Copyright (c) 2010-2014, Salvatore Sanfilippo <antirez at gmail dot com>\n"
	 "Copyright (c) 2010-2013, Pieter Noordhuis <pcnoordhuis at gmail dot com>\n"
	 "\n"
	 "All rights reserved.\n"
	 "\n"
	 "Redistribution and use in source and binary forms, with or without\n"
	 "modification, are permitted provided that the following conditions are met:\n"
	 "\n"
	 "* Redistributions of source code must retain the above copyright notice,\n"
	 "  this list of conditions and the following disclaimer.\n"
	 "\n"
	 "* Redistributions in binary form must reproduce the above copyright notice,\n"
	 "  this list of conditions and the following disclaimer in the documentation\n"
	 "  and/or other materials provided with the distribution.\n"
	 "\n"
	 "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\n"
	 "ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
	 "WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
	 "DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR\n"
	 "ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
	 "(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
	 "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n"
	 "ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
	 "(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
	 "SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
	 "\n"
	 "\n"
	 );
}
